spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hxmall?serverTimezone=UTC
    username: root
    password: 724221yyds

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.shirley.hxmall.entity
